version: '3.8'

services:
  notdiamond-adapter:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NOTDIAMOND_API_KEY=${NOTDIAMOND_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 